### ISSUE TITLE
Congratulation message for HTML5 CROSSWORD PUZZLE GAME

### ISSUE THREAD

**Issue by manishaDomun** [habibieamrullah/HTML5-Crossword-Puzzle-Game#1]
Dear Mr Amrullah

First of all thank you for sharing the crossword. I am humbly requesting whether it is possible to add a successful message popup on completing the crossword? 
If the audience to be targeted are kids.. they would like some feedbacks upon completion. Can you help?

**Comment by habibieamrullah** [comment]
I can.. but if you are willing to donate I will help you on it soon.
